apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-app
  ports:
  - protocol: "TCP"
    port: 7777
    targetPort: 3306
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-app
spec:
  selector:
    matchLabels:
      app: mysql-app
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
      - name: mysql-app
        image: cccontainerregistry1.azurecr.io/mysql:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306